"""Génération des schémas TypeScript (zod) depuis les modèles Pydantic.

Stratégie Phase 0 : on exporte d'abord en JSON Schema, puis on utilise un post-processing
minimal pour produire un fichier TypeScript avec types + zod schemas. En Phase 1+, on
passera à un outil plus complet si le volume le justifie.
"""
from __future__ import annotations

import sys
from pathlib import Path

from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).parent.parent))

from schemas.feature_flag import FeatureFlagRead, FeatureFlagUpdate

OUTPUT_DIR = Path(__file__).parent.parent.parent.parent / "packages" / "shared-types" / "src" / "generated"
OUTPUT_FILE = OUTPUT_DIR / "schemas.ts"

EXPORTED_MODELS: list[type[BaseModel]] = [
    FeatureFlagRead,
    FeatureFlagUpdate,
]


def pydantic_to_ts_type(schema: dict) -> str:
    lines = [f"export interface {schema['title']} {{"]
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    for name, prop in properties.items():
        ts_type = _jsonschema_to_ts(prop)
        optional_marker = "" if name in required else "?"
        lines.append(f"  {name}{optional_marker}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _jsonschema_to_ts(prop: dict) -> str:
    t = prop.get("type")
    if t == "string":
        return "string"
    if t == "integer" or t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        items = prop.get("items", {})
        return f"{_jsonschema_to_ts(items)}[]"
    if t == "null":
        return "null"
    if "anyOf" in prop:
        return " | ".join(_jsonschema_to_ts(opt) for opt in prop["anyOf"])
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]
    return "unknown"


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    parts = [
        "// AUTO-GENERATED by apps/backend/scripts/generate_ts_schemas.py",
        "// DO NOT EDIT — regenerate with: cd apps/backend && source .venv/bin/activate && python scripts/generate_ts_schemas.py",
        "",
    ]
    for model in EXPORTED_MODELS:
        schema = model.model_json_schema()
        parts.append(pydantic_to_ts_type(schema))
        parts.append("")

    OUTPUT_FILE.write_text("\n".join(parts))
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
